orbs:
  node: circleci/node@6.2.0

version: 2.1

parameters:
  node_version:
    type: string
    default: '20.9.0'

commands:
  install_deps:
    steps:
      - node/install-packages:
          pkg-manager: yarn
          cache-version: v1-all
          cache-only-lockfile: true
          app-dir: ~/repo
          override-ci-command: yarn install --pure-lockfile --no-progress

jobs:
  build:
    executor:
      name: node/default
      tag: << pipeline.parameters.node_version >>
    working_directory: ~/repo
    steps:
      - checkout
      - install_deps
      - run: yarn test
      - run: yarn type-check
      - run: yarn test
      - run: yarn lint:ci
